apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 7siri/order-service:latest
        ports:
        - containerPort: 80
#webhook test
#weebhook final test
#wehook final test after fix
