apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/<13siri06>/gitops-manifests.git
    targetRevision: HEAD
    path: apps/order-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true